const menuItems = [
  // Pizza Category
  {
    id: 1,
    category: "Pizza",
    title: "Margherita",
    desc: "Klasik Margherita pizza, taze mozzarella, domates sosu ve fesleğen ile hazırlanır. Sade ama lezzetli bir seçenek sunar. İtalyan mutfağının klasiklerinden biridir.",
    img: "./recipes/margherita.jpg",
    price: 12,
  },
  {
    id: 2,
    category: "Pizza",
    title: "Pepperoni",
    desc: "İtalyan sosisleriyle zenginleştirilmiş klasik pizza. Tatlı domates sosu ve erimiş mozzarella peyniriyle birleşir. Et severler için mükemmel bir seçenek.",
    img: "./recipes/pepperoni.jpg",
    price: 14,
  },
  {
    id: 3,
    category: "Pizza",
    title: "Meat Lovers",
    desc: "Bacon, sucuk, jambon ve sosis ile zenginleştirilmiş et severler için ideal bir pizza. Lezzetli ve doyurucu bir seçenek.",
    img: "./recipes/meat-lovers.jpg",
    price: 18,
    tag: "recommended",
  },
  {
    id: 4,
    category: "Pizza",
    title: "Hawaiian",
    desc: "Jambon ve ananasla zenginleştirilmiş tatlı ve tuzlu bir pizza deneyimi. Tropikal tatlar arayanlar için mükemmel bir tercihtir.",
    img: "./recipes/hawaiian.jpg",
    price: 15,
    tag: "special",
  },
  {
    id: 5,
    category: "Pizza",
    title: "BBQ Chicken",
    desc: "Izgarada pişmiş tavuk, barbekü sosu, soğan ve mısırla hazırlanan bu pizza, barbekü tatlarını sevenler için mükemmel bir seçenek sunar.",
    img: "./recipes/bbq-chicken.jpg",
    price: 16,
  },
  {
    id: 6,
    category: "Pizza",
    title: "Four Cheese",
    desc: "Mozzarella, cheddar, parmesan ve gorgonzola peynirlerinin zengin karışımıyla hazırlanan bu pizza, peynir severler için harika bir alternatiftir.",
    img: "./recipes/four-cheese.jpg",
    price: 17,
  },
  {
    id: 7,
    category: "Pizza",
    title: "Buffalo Chicken",
    desc: "Baharatlı buffalo sosu, tavuk, mavi peynir ve taze sebzelerle hazırlanan bu pizza, baharatlı lezzetleri sevenler için mükemmel bir tercihtir.",
    img: "./recipes/buffalo-chicken.jpg",
    price: 16,
  },
  {
    id: 8,
    category: "Pizza",
    title: "Supreme",
    desc: "Biber, zeytin, sucuk, mantar ve soğanla zenginleştirilmiş bu pizza, çok sevilen malzemelerle hazırlanır. Tüm pizza severler için mükemmel bir tercihtir.",
    img: "./recipes/supreme.jpg",
    price: 17,
  },
  {
    id: 9,
    category: "Pizza",
    title: "BBQ Meatball",
    desc: "Barbekü sosuyla pişirilmiş köfteler ve mozzarella peyniriyle hazırlanan bu pizza, et severler için doyurucu bir seçenek sunar.",
    img: "./recipes/bbq-meatball.jpg",
    price: 18,
    tag: "special",
  },
  {
    id: 10,
    category: "Pizza",
    title: "Chicken Alfredo",
    desc: "Izgara tavuk, alfredo sosu, mozzarella peyniri ve domatesle hazırlanan bu pizza, zengin ve kremsi lezzetleri sevenler için mükemmeldir.",
    img: "./recipes/chicken-alfredo.jpg",
    price: 17,
    tag: "recommended",
  },

  // Hamburger Category
  {
    id: 11,
    category: "Hamburger",
    title: "Classic Cheeseburger",
    desc: "Taze hamburger ekmeği içinde, lezzetli dana eti, cheddar peyniri ve taze sebzelerle hazırlanan bu klasik burger, her damağa hitap eder.",
    img: "./recipes/classic-cheeseburger.jpg",
    price: 12,
  },
  {
    id: 12,
    category: "Hamburger",
    title: "Bacon Cheeseburger",
    desc: "Dana eti, cheddar peyniri ve çıtır bacon dilimleriyle zenginleştirilmiş bu burger, lezzetli bir bacon severler için harika bir alternatif sunar.",
    img: "./recipes/bacon-cheeseburger.jpg",
    price: 14,
    tag: "recommended",
  },
  {
    id: 13,
    category: "Hamburger",
    title: "BBQ Burger",
    desc: "Izgara dana eti, barbekü sosu, peynir ve soğan halkalarıyla hazırlanan bu burger, tatlı ve dumanlı bir lezzet sunar.",
    img: "./recipes/bbq-burger.jpg",
    price: 15,
  },
  {
    id: 14,
    category: "Hamburger",
    title: "Cheese Lover's Burger",
    desc: "Çift peynirli, burger ekmeği arasında cheddar ve mozzarella peynirleriyle servis edilen bu seçenek, peynir severler için mükemmel bir tercihtir.",
    img: "./recipes/cheese-lovers-burger.jpg",
    price: 14,
    tag: "special",
  },
  {
    id: 15,
    category: "Hamburger",
    title: "Mushroom Swiss Burger",
    desc: "Izgara dana eti, erimiş swiss peyniri ve sote mantarlarla hazırlanan bu burger, mantar severler için harika bir seçimdir.",
    img: "./recipes/mushroom-swiss-burger.jpg",
    price: 14,
  },
  {
    id: 16,
    category: "Hamburger",
    title: "Spicy Jalapeño Burger",
    desc: "Acı jalapeño biberleri, cheddar peyniri ve etli burger ile hazırlanan bu seçenek, baharatlı tatları sevenler için mükemmeldir.",
    img: "./recipes/spicy-jalapeno-burger.jpg",
    price: 14,
    tag: "recommended",
  },
  {
    id: 17,
    category: "Hamburger",
    title: "Chicken Burger",
    desc: "Izgara tavuk, marullarla zenginleştirilmiş taze bir burger. Tavuk sevenler için lezzetli ve sağlıklı bir seçenek.",
    img: "./recipes/chicken-burger.jpg",
    price: 12,
  },
  {
    id: 18,
    category: "Hamburger",
    title: "Beef & Bacon Burger",
    desc: "Klasik et, bacon dilimleri ve cheddar peyniriyle hazırlanan bu burger, et severler için harika bir tercihtir. Hem lezzetli hem doyurucudur.",
    img: "./recipes/beef-bacon-burger.jpg",
    price: 15,
    tag: "special",
  },
  {
    id: 19,
    category: "Hamburger",
    title: "BBQ Chicken Burger",
    desc: "Barbekü tavuk, peynir, soğan halkaları ve barbekü sosu ile hazırlanan bu burger, barbekü lezzetlerini sevenler için mükemmel bir alternatiftir.",
    img: "./recipes/bbq-chicken-burger.jpg",
    price: 13,
  },
  {
    id: 20,
    category: "Hamburger",
    title: "Hawaiian Burger",
    desc: "Jambon, ananas ve peynirle hazırlanan tatlı ve tuzlu bir burger deneyimi. Tropikal tatları sevenler için harika bir alternatif.",
    img: "./recipes/hawaiian-burger.jpg",
    price: 14,
  },

  // Grill & Barbecue Category
  {
    id: 21,
    category: "Grill",
    title: "Grilled Chicken",
    desc: "Izgarada pişirilmiş tavuk, baharatlar ve marinadlarla zenginleştirilir. Lezzetli ve sulu bir et deneyimi sunar. Tavuk severler için mükemmel bir seçenek.",
    img: "./recipes/grilled-chicken.jpg",
    price: 14,
  },
  {
    id: 22,
    category: "Grill",
    title: "Grilled Salmon",
    desc: "Izgarada pişirilmiş somon, zeytinyağı ve limon ile tatlandırılır. Sağlıklı ve lezzetli bir deniz ürünü alternatifi sunar.",
    img: "./recipes/grilled-salmon.jpg",
    price: 18,
    tag: "recommended",
  },
  {
    id: 23,
    category: "Grill",
    title: "Grilled Shrimp Skewers",
    desc: "Taze karidesler, ızgarada pişirilmiş ve baharatlarla tatlandırılmıştır. Sağlıklı ve lezzetli bir deniz mahsulü alternatifi.",
    img: "./recipes/grilled-shrimp-skewers.jpg",
    price: 16,
    tag: "special",
  },
  {
    id: 24,
    category: "Grill",
    title: "Grilled Lamb Chops",
    desc: "Lamb chops, ızgarada pişirilip baharatlarla zenginleştirilir. Her ısırıkta yumuşak ve etli dokusu ile mükemmel bir lezzet sunar. Lamb chops severler için mükemmel bir alternatiftir.",
    img: "./recipes/grilled-lamb-chops.jpg",
    price: 22,
  },
  {
    id: 25,
    category: "Grill",
    title: "Grilled Steak",
    desc: "Sadece en iyi et kullanılarak yapılan bu ızgara biftek, et severler için mükemmel bir seçenek sunar. Baharatlarla tatlandırılmış ve mükemmel pişirilmiştir.",
    img: "./recipes/grilled-steak.jpg",
    price: 20,
    tag: "recommended",
  },
  {
    id: 26,
    category: "Grill",
    title: "Grilled Portobello Mushroom",
    desc: "Izgarada pişirilmiş büyük Portobello mantarları, etli dokusu ve zengin lezzetiyle öne çıkar. Hem vejetaryenler hem de et severler için mükemmel bir seçenek sunar. Lezzetli ve doyurucu bir alternatif.",
    img: "./recipes/grilled-portobello-mushroom.jpg",
    price: 13,
  },
  {
    id: 27,
    category: "Barbecue",
    title: "BBQ Chicken",
    desc: "Tavuk, barbekü sosuyla kaplanıp fırında ya da ızgarada pişirilir ve dumanlı bir aroma alır. Zengin ve tatlı bir barbekü sosu ile servis edilir. Et ve barbekü severler için mükemmel bir tercih.",
    img: "./recipes/bbq-chicken.jpg",
    price: 14,
  },
  {
    id: 28,
    category: "Barbecue",
    title: "BBQ Ribs",
    desc: "Izgara kaburgalar, tatlı ve dumanlı barbekü sosuyla kaplanır. Yavaş pişirilerek etin kemikten ayrılması sağlanır. Mükemmel bir barbekü deneyimi sunar.",
    img: "./recipes/bbq-ribs.jpg",
    price: 16,
    tag: "special",
  },
  {
    id: 29,
    category: "Barbecue",
    title: "BBQ Chicken Wings",
    desc: "Izgara kanatlar, tatlı barbekü sosu ile kaplanıp servis edilir. Tüm kanat severler için doyurucu ve lezzetli bir alternatiftir.",
    img: "./recipes/bbq-chicken-wings.jpg",
    price: 12,
  },

  // Pasta Category
  {
    id: 30,
    category: "Pasta",
    title: "Spaghetti Bolognese",
    desc: "Dana eti, domates sosu ve baharatlarla hazırlanan bu klasik İtalyan yemeği, her damağa hitap eder. Zengin lezzeti ile mükemmel bir alternatif.",
    img: "./recipes/spaghetti-bolognese.jpg",
    price: 14,
  },
  {
    id: 31,
    category: "Pasta",
    title: "Fettuccine Alfredo",
    desc: "Kremalı fettuccine makarna, Parmesan peyniri ve tereyağı ile yapılır. Zengin ve lezzetli bir alternatif sunar. Klasik İtalyan makarnalarından biridir.",
    img: "./recipes/fettuccine-alfredo.jpg",
    price: 15,
    tag: "recommended",
  },
  {
    id: 32,
    category: "Pasta",
    title: "Penne Arrabbiata",
    desc: "Acı domates sosu, sarımsak ve baharatlarla hazırlanan bu makarna, baharatlı lezzetler sevenler için mükemmel bir seçenek sunar.",
    img: "./recipes/penne-arrabbiata.jpg",
    price: 13,
  },
  {
    id: 33,
    category: "Pasta",
    title: "Seafood Pasta",
    desc: "Taze deniz mahsulleri, kremalı sos ve makarna ile yapılan bu yemek, deniz ürünü sevenler için mükemmel bir alternatiftir. Hafif ama doyurucu bir lezzet sunar.",
    img: "./recipes/seafood-pasta.jpg",
    price: 16,
  },
  {
    id: 34,
    category: "Pasta",
    title: "Lasagna",
    desc: "Katmanlı makarna, et, peynir ve beşamel sosu ile hazırlanan bu yemek, doyurucu ve lezzetlidir. İtalyan mutfağının en sevilen yemeklerinden biridir.",
    img: "./recipes/lasagna.jpg",
    price: 17,
    tag: "special",
  },
  {
    id: 35,
    category: "Pasta",
    title: "Pesto Pasta",
    desc: "Taze fesleğen, sarımsak ve çam fıstığıyla yapılan pesto sosu ile hazırlanmış makarna, lezzetli ve besleyici bir alternatiftir.",
    img: "./recipes/pesto-pasta.jpg",
    price: 14,
    tag: "recommended",
  },
  {
    id: 36,
    category: "Pasta",
    title: "Vegetarian Lasagna",
    desc: "Sebzelerle yapılan bu lasagna, et yerine taze malzemelerle zenginleştirilir. Hafif ama doyurucu bir yemek alternatifi sunar.",
    img: "./recipes/vegetarian-lasagna.jpg",
    price: 15,
  },
  {
    id: 37,
    category: "Pasta",
    title: "Vegan Pasta",
    desc: "Sebze, tofu ve zeytinyağı ile yapılan bu makarna, sağlıklı ve lezzetli bir alternatiftir. Sebze severler için mükemmel bir seçim.",
    img: "./recipes/vegan-pasta.jpg",
    price: 13,
    tag: "special",
  },

  // Vegetarian Category
  {
    id: 38,
    category: "Vegetarian",
    title: "Vegetable Stir Fry",
    desc: "Taze sebzelerle hazırlanan bu stir fry, soya sosu ve baharatlarla tatlandırılır. Hafif ama lezzetli bir öğün sunar. Sağlıklı ve vejetaryenler için mükemmeldir.",
    img: "./recipes/vegetable-stir-fry.jpg",
    price: 12,
  },
  {
    id: 39,
    category: "Vegetarian",
    title: "Grilled Veggie Tacos",
    desc: "Izgarada pişirilmiş sebzeler, mısır ve baharatlarla tatlandırılmıştır. Vejetaryenler için sağlıklı ve lezzetli bir alternatif sunar.",
    img: "./recipes/grilled-veggie-tacos.jpg",
    price: 10,
    tag: "recommended",
  },
  {
    id: 40,
    category: "Vegetarian",
    title: "Spinach and Ricotta Ravioli",
    desc: "Ispanak ve ricotta peyniriyle doldurulmuş ravioli, hafif ama doyurucu bir alternatiftir. Taze malzemelerle hazırlanan bu yemek, vejetaryenler için mükemmel bir seçim.",
    img: "./recipes/spinach-ricotta-ravioli.jpg",
    price: 14,
    tag: "special",
  },
  {
    id: 41,
    category: "Vegetarian",
    title: "Vegetarian Pizza",
    desc: "Sebzeler, zeytin, mantar ve biberle hazırlanan bu pizza, vejetaryenler için harika bir alternatiftir. Sağlıklı ve lezzetli bir seçenek sunar.",
    img: "./recipes/vegetarian-pizza.jpg",
    price: 13,
  },
  {
    id: 42,
    category: "Vegetarian",
    title: "Tofu Stir Fry",
    desc: "Yumuşak tofu, taze sebzelerle birlikte wokta pişirilir ve soya sosu ile tatlandırılır. Hafif ama lezzetli bir yemek isteyenler için mükemmel bir seçenek.",
    img: "./recipes/tofu-stir-fry.jpg",
    price: 13,
  },
  {
    id: 43,
    category: "Vegetarian",
    title: "Veggie Burger",
    desc: "Sebzeler, mercimek ve tahıllarla yapılan vejetaryen burger, taze malzemelerle servis edilir. Vejetaryenler için sağlıklı ve doyurucu bir seçenek sunar.",
    img: "./recipes/veggie-burger.jpg",
    price: 13,
    tag: "recommended",
  },
  {
    id: 44,
    category: "Vegetarian",
    title: "Cauliflower Wings",
    desc: "Karnabahar, baharatlı soslarla kaplanarak fırınlanır. Hem lezzetli hem sağlıklı bir atıştırmalık alternatifi sunar. Vejetaryenler için mükemmel bir seçenektir.",
    img: "./recipes/cauliflower-wings.jpg",
    price: 12,
  },
  {
    id: 45,
    category: "Vegetarian",
    title: "Vegetable Curry",
    desc: "Taze sebzeler, hindistancevizi sütü ve baharatlarla yapılan bu curry, vejetaryenler için harika bir seçenektir. Zengin ve doyurucudur.",
    img: "./recipes/vegetable-curry.jpg",
    price: 14,
  },
  {
    id: 46,
    category: "Vegetarian",
    title: "Stuffed Bell Peppers",
    desc: "Biberler, pirinç, sebzeler ve peynirle doldurulur. Hafif ama lezzetli bir yemek seçeneği sunar. Vejetaryenler için sağlıklı ve doyurucu bir alternatiftir.",
    img: "./recipes/stuffed-bell-peppers.jpg",
    price: 13,
    tag: "special",
  },
];

export const services = [
  {
    title: "Fast Delivery",
    image: "",
    desc: "Your order is prepared swiftly and delivered to your doorstep.",
  },
  {
    title: "Super Taste",
    image: "",
    desc: "Our pizzas are crafted with the freshest ingredients sourced from local suppliers.",
  },
  {
    title: "Easy Order",
    image: "",
    desc: "Ordering is a breeze with our user-friendly platform, ensuring a seamless experience.",
  },
];

export default menuItems;
